#!/bin/zsh

SUDO_COMMAND=pkexec
#SUDO_COMMAND=gksu
#SUDO_COMMAND=kdesu
#SUDO_COMMAND=sudo

if [[ -n $1 ]]
then
  case "$1" in
    high|power)
      $SUDO_COMMAND cpupower frequency-set -g performance
      ;;
    up)
      if grep -qF schedutil /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
      then
        $SUDO_COMMAND cpupower frequency-set -g schedutil
      else
        $SUDO_COMMAND cpupower frequency-set -g performance
      fi
      ;;
    down)
      $SUDO_COMMAND cpupower frequency-set -g powersave
      ;;
    *)
      notify-send -i cpu -a "CPU Governor Controller" -t 3 -u low -e $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
      ;;
  esac
else
  avilable_governors=($(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors))
  #avilable_governors=(powersave performance)
  #avilable_governors=(powersave schedutil performance)

  gov=$(yad --title="CPU Govornor Controller" --window-icon=cpu --width=300 --height=500 --text="current governor is [$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)]" --list --column=governor $avilable_governors)

  if (( ? == 0 ))
  then
    $SUDO_COMMAND cpupower frequency-set -g ${gov%%|*}
  fi
fi


